# Generated by Django 5.2.7 on 2026-07-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilehealth_healthmetriclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMatric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, choices=[('WEIGHT_GAIN', 'Weight Gain'), ('WEIGHT_LOSS', 'Weight Loss'), ('MAINTAINING', 'Maintaining')], max_length=20, null=True)),
                ('daily_water_intake', models.FloatField(blank=True, null=True)),
                ('daily_steps', models.IntegerField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.DeleteModel(
            name='HealthMetricLog',
        ),
        migrations.AddIndex(
            model_name='profilematric',
            index=models.Index(fields=['user', 'created_date'], name='user_created_date_idx'),
        ),
    ]
