# Generated by Django 5.2.7 on 2026-01-01 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthprofile_bmi_alter_dailyhealthmetric_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthjournal',
            old_name='workout_plan',
            new_name='exercise_plan',
        ),
        migrations.RenameModel(
            old_name='WorkoutPlan',
            new_name='ExercisePlan',
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('repetitions', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.exercise')),
                ('exercise_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.exerciseplan')),
            ],
            options={
                'unique_together': {('exercise_plan', 'exercise')},
            },
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
