# Generated by Django 5.2.7 on 2026-01-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_rename_workout_plan_healthjournal_exercise_plan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanExercise',
            new_name='ExercisePlant_Exercise',
        ),
    ]
