# Generated by Django 5.2.7 on 2026-01-05 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_rename_planexercise_exerciseplant_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='experience_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expertise',
            field=models.CharField(choices=[('WEIGHT_GAIN', 'Weight Gain'), ('WEIGHT_LOSS', 'Weight Loss'), ('MAINTAINING', 'Maintaining')], default='MAINTAINING', max_length=30),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='health.expert')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
