# Generated by Django 5.2.7 on 2026-01-07 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_expert_experience_year_alter_expert_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhealthmetric',
            name='calories_burned',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyhealthmetric',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyhealthmetric',
            name='water_intake',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='goal',
            field=models.CharField(choices=[('WEIGHT_GAIN', 'Weight Gain'), ('WEIGHT_LOSS', 'Weight Loss'), ('MAINTAINING', 'Maintaining')], default='MAINTAINING', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=50),
        ),
    ]
