# Generated by Django 5.2.7 on 2026-01-07 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_dailyhealthmetric_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
