# Generated by Django 5.2.7 on 2026-01-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthjournal',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthjournal',
            name='exercise_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.exerciseplan'),
        ),
    ]
